Android_app.path=src/test/resources/app/mda-2.2.0-25.apk
iOS_app.path=src/test/resources/app/SauceLabs-Demo-App-With-TestFairy.ipa
api.timeout=30
Android_sauceFileID=4d14ded1-335e-437b-a54b-350fad9492c2
iOS_sauceFileID=0502bbde-7cdd-42c1-a5cf-1cad191e608b